# Generated by Django 6.0.3 on 2026-03-18 15:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('common_uses', models.TextField(help_text='Common conditions this medication is used for')),
                ('description', models.TextField(blank=True)),
                ('dosage_note', models.TextField(help_text='General dosage guidance')),
                ('side_effects', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('is_over_the_counter', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutbreakAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('alert_level', models.CharField(choices=[('info', 'Information'), ('watch', 'Watch'), ('warning', 'Warning'), ('emergency', 'Emergency')], max_length=20)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(blank=True)),
                ('prevention_tips', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('date_reported', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_text', models.TextField(help_text="User's description of symptoms")),
                ('temperature', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(35.0), django.core.validators.MaxValueValidator(42.0)])),
                ('duration_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('age_group', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_fever', models.BooleanField(default=False)),
                ('has_cough', models.BooleanField(default=False)),
                ('has_headache', models.BooleanField(default=False)),
                ('has_fatigue', models.BooleanField(default=False)),
                ('has_body_aches', models.BooleanField(default=False)),
                ('has_sore_throat', models.BooleanField(default=False)),
                ('has_difficulty_breathing', models.BooleanField(default=False)),
                ('has_nausea', models.BooleanField(default=False)),
                ('has_diarrhea', models.BooleanField(default=False)),
                ('has_rash', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('home', 'Rest at Home'), ('clinic', 'Visit Clinic'), ('emergency', 'Emergency Care')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('possible_condition', models.CharField(blank=True, max_length=200)),
                ('ai_analysis', models.TextField(blank=True, help_text='Detailed AI analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptom_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_result', to='triage.symptomlog')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('health_worker', 'Health Worker'), ('admin', 'Administrator')], default='patient', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('age_group', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Specific notes for this recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.medication')),
                ('triage_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_recommendations', to='triage.triageresult')),
            ],
            options={
                'unique_together': {('triage_result', 'medication')},
            },
        ),
    ]
